 
import "./globals.css";
import Header from "@/components/UI/Header";

export const metadata = {
  title: "Grocery Store",
  description: "Generated by  David",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
